import type { ProfileData, Project } from '@shared/types/portfolio.types'

export const terminalTestProfile: ProfileData = {
  name: 'Test Engineer',
  brandName: 'test-engineer',
  title: 'Software Engineer',
  about: ['Builds reliable systems.', 'Enjoys clear interfaces.'],
  githubUsername: 'test-engineer',
  githubUrl: 'https://github.com/test-engineer',
  repositoryUrl: 'https://github.com/test-engineer/portfolio',
  githubLabel: 'GitHub',
  linkedinUrl: 'https://www.linkedin.com/in/test-engineer',
  linkedinConnectionCount: 500,
  linkedinLabel: 'LinkedIn',
  linkedinConnectionsLabel: 'connections',
  heroStatusLabel: 'Systems online',
  heroTerminalPath: '~/portfolio',
  heroTerminalDirectories: ['projects', 'skills'],
  heroTerminalPrompt: '_',
  heroCertificationsHeading: 'Certifications',
  heroCertifications: [
    {
      credentialUrl: 'https://example.com/credential',
      imageUrl: 'https://example.com/badge.png',
      imageAlt: 'Test certification badge',
      imageWidth: 100,
      imageHeight: 100,
    },
  ],
  contributionsLoadingLabel: 'Loading contributions',
  contributionsSuffixLabel: 'contributions',
  aboutHeadingLead: 'About',
  aboutHeadingAccent: 'the engineer',
  aboutIntro: 'A test profile for terminal behavior.',
  techStackSectionEyebrow: 'Tools',
  techStackSectionTitle: 'Technology stack',
  techStackSectionDescription: 'Technologies used in projects.',
  projectsSectionEyebrow: 'Work',
  projectsSectionTitle: 'Projects',
  projectsSectionDescription: 'Selected test projects.',
  projectLiveLabel: 'View live',
  projectSourceLabel: 'View source',
  educationSectionEyebrow: 'Learning',
  educationSectionTitle: 'Education',
  educationSectionDescription: 'Selected education.',
  footerAttribution: 'Built for testing.',
}

export const terminalTestProjects: Project[] = [
  {
    id: 'alpha-project',
    title: 'Alpha Project',
    summary: 'The first deterministic test project.',
    highlights: ['Reliable'],
    stack: ['TypeScript'],
    liveUrl: 'https://example.com/alpha',
    repoUrl: 'https://github.com/test-engineer/alpha',
  },
  {
    id: 'beta-project',
    title: 'Beta Project',
    summary: 'The second deterministic test project.',
    highlights: ['Accessible'],
    stack: ['React'],
    repoUrl: 'https://github.com/test-engineer/beta',
  },
]
