import { motion } from 'framer-motion'
import { FiArrowRight, FiGithub } from 'react-icons/fi'
import type { ProfileData } from '../types/portfolio'

interface HeroSectionProps {
  profile: ProfileData
}

export function HeroSection({ profile }: HeroSectionProps) {
  return (
    <section className="section-wrap flex items-center py-12 lg:h-[calc(100vh-5rem)] lg:py-0" id="home">
      <div className="grid w-full items-center gap-10 lg:grid-cols-[1.08fr_0.92fr] lg:gap-12">
        <motion.div
          initial={{ opacity: 0, x: -30 }}
          transition={{ duration: 0.6 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true, amount: 0.4 }}
        >
          <span className="inline-flex rounded-full border border-accent-200 bg-accent-50 px-4 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-accent-700 dark:border-accent-500/40 dark:bg-accent-500/10 dark:text-accent-300">
            AI Systems • Cloud Platforms • DevEx
          </span>
          <h1 className="mt-6 text-4xl font-semibold tracking-tight text-slate-900 dark:text-slate-50 md:text-6xl">
            {profile.name}
          </h1>
          <p className="mt-4 text-xl font-medium text-accent-700 dark:text-accent-300 md:text-2xl">
            {profile.title}
          </p>
          <p className="mt-5 max-w-2xl text-base leading-relaxed text-slate-600 dark:text-slate-300 md:text-lg">
            {profile.tagline}
          </p>
          <div className="mt-8 flex flex-wrap gap-4">
            <a
              className="inline-flex items-center gap-2 rounded-full bg-accent-600 px-6 py-3 text-sm font-semibold text-white transition hover:bg-accent-700"
              href="#projects"
            >
              View Projects
              <FiArrowRight className="h-4 w-4" />
            </a>
            <a
              className="inline-flex items-center gap-2 rounded-full border border-slate-300 bg-white/75 px-6 py-3 text-sm font-semibold text-slate-800 transition hover:border-accent-500 hover:text-accent-700 dark:border-slate-700 dark:bg-slate-900/70 dark:text-slate-100 dark:hover:border-accent-400 dark:hover:text-accent-300"
              href={profile.githubUrl}
              rel="noreferrer"
              target="_blank"
            >
              GitHub
              <FiGithub className="h-4 w-4" />
            </a>
          </div>
          <div className="mt-8 grid max-w-xl grid-cols-3 gap-3">
            {profile.stats.map((stat) => (
              <div
                className="glass-panel rounded-2xl border border-slate-200/80 p-4 dark:border-slate-700/60"
                key={stat.label}
              >
                <p className="text-lg font-semibold text-slate-900 dark:text-slate-50">
                  {stat.value}
                </p>
                <p className="mt-1 text-xs leading-snug text-slate-600 dark:text-slate-300">
                  {stat.label}
                </p>
              </div>
            ))}
          </div>
        </motion.div>
        <motion.aside
          className="glass-panel p-5 sm:p-7"
          initial={{ opacity: 0, x: 30 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true, amount: 0.35 }}
        >
          <div className="mb-4 flex items-center justify-between">
            <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-50">
              GitHub Snapshot
            </h2>
            <span className="rounded-full border border-slate-300/80 px-3 py-1 text-xs font-medium text-slate-600 dark:border-slate-700 dark:text-slate-300">
              Local SVG
            </span>
          </div>
          <p className="text-sm leading-relaxed text-slate-600 dark:text-slate-300">
            This contribution chart is generated by a weekly GitHub Actions workflow and committed into the repository.
          </p>
          <div className="mt-5 overflow-hidden rounded-2xl border border-slate-200/80 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-900/60">
            <img
              alt={`GitHub contribution activity for ${profile.githubUsername}`}
              className="h-auto w-full rounded-xl"
              loading="eager"
              src="/assets/github-contrib.svg"
            />
          </div>
          <a
            className="mt-5 inline-flex items-center gap-2 rounded-full border border-accent-400/70 px-5 py-2 text-sm font-semibold text-accent-700 transition hover:bg-accent-500 hover:text-white dark:border-accent-300/60 dark:text-accent-300 dark:hover:bg-accent-500 dark:hover:text-white"
            href={profile.githubUrl}
            rel="noreferrer"
            target="_blank"
          >
            Open @{profile.githubUsername}
            <FiArrowRight className="h-4 w-4" />
          </a>
        </motion.aside>
      </div>
    </section>
  )
}
